name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: [3.8, 3.9, 3.11]

      - name: Install dependencies
        run: |
          pip install poetry
          make install
          poetry add pytest pytest-cov codeclimate-test-reporter

      - name: Run tests and collect coverage
        run: |
          poetry run --cov=gendiff --cov-report xml

      - name: Upload coverage to Code Climate
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          wget -O cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
          chmod +x cc-test-reporter
          ./cc-test-reporter format-coverage coverage.xml --input-type coverage.py
          ./cc-test-reporter upload-coverage
